# frozen_string_literal: true
source 'https://rubygems.org'

gem 'bosh_common'
gem 'bosh_cpi'
gem 'ruby-libvirt'
gem 'httpclient',    '=2.7.1'
gem 'membrane'
gem 'nokogiri'

group :development, :test do
  gem 'rspec', '~> 3.3.0'
  gem 'rake', '~>10.3.2'
  gem 'byebug'
end
